version: 2.1

orbs:
  python: circleci/python@0.2.1
  aws-s3: circleci/aws-s3@1.0.15

jobs:
  upload_to_s3:
    parameters:
      data_source:
        type: string
        default: 'lodes'
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run: mkdir data
      - run: chmod -R 755 ./extract_data/*
      - run: python3 ./extract_data/data_from_web.py << parameters.data_source >>
      - aws-s3/copy:
          aws-access-key-id: access_key
          aws-secret-access-key: secret_key
          aws-region: region
          from: './data/*'
          to: 's3://nlt-us-census-demo/'

workflows:
  main:
    jobs:
      - upload_to_s3
