version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-print:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ls -la

workflows:
  main:
    jobs:
      - build-and-print
