version: 2.1

orbs:
  python: circleci/python@0.2.1

parameters:
  data_source:
    type: string
    default: 'all'

jobs:
  build-and-print:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./extract_data/data_from_web.py << pipeline.data_source >>

workflows:
  main:
    jobs:
      - build-and-print
