version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-print:
    parameters:
      data_source:
        type: string
        default: 'all'
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./extract_data/data_from_web.py << parameters.data_source >>

workflows:
  main:
    jobs:
      - build-and-print
